###
# @name Register user
POST http://localhost:8000/api/v1/users/register-user
Content-Type: application/json

{
    "email": "gigi@gmail.com",
    "password": "GigiGigiGigi",
    "username": "Gigi2",
    "firstName": "Gigi",
    "lastName": "Bibi"
}

###
# @name Get all users
GET http://localhost:8000/api/v1/users/users

###
# @name Activate user
POST http://localhost:8000/api/v1/users/activate-account
Content-Type: application/json

{
    "email": "gigi@gmail.com",
    "code": "RPQ4WJ"
}

###
# @name Regenerate code
POST http://localhost:8000/api/v1/users/regenerate-code
Content-Type: application/json

{
    "email": "gigi@gmail.com"
}

###
# @name Login
POST http://localhost:8000/api/v1/authentication/login
Content-Type: application/json

{
    "username": "Gigi",
    "password": "GigiGigiGigi"
}